language: node_js

notifications:
  email: false

sudo: false

cache:
  yarn: true
  directories:
    - node_modules

node_js:
  - '10'

install:
  - yarn install --frozen-lockfile

script:
  # Build the client and server
  - yarn build
  # Run the tests
  - yarn test
